# Generated by Django 5.0.6 on 2024-06-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'ecom_admin',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'ecom_category',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ecom_country',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.TextField()),
                ('phone', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ecom_users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('longDescription', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('price', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.category')),
            ],
            options={
                'db_table': 'ecom_products',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('address', models.CharField()),
                ('postal', models.CharField(unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.users')),
            ],
            options={
                'db_table': 'ecom_address',
            },
        ),
    ]
