# Generated by Django 5.0.6 on 2024-06-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.users')),
            ],
        ),
    ]
