# Generated by Django 5.0.6 on 2024-06-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0002_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='ecom_cart',
        ),
    ]
