# Generated by Django 5.0.6 on 2024-06-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECom', '0004_cart_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECom.users')),
            ],
            options={
                'db_table': 'ecom_checkout',
            },
        ),
    ]
